version: '2'
services:

  livingcost-db:
    image: 'mongo:latest'
    container_name: 'livingcost-db'
    command: mongod --port 27017  
    ports:
      - '27017:27017'

  livingcost-ms:
    container_name: 'livingcost-ms'
    build: .
    ports:
      - '3000:3000'

    depends_on:
      - 'livingcost-db'
    links:
      - livingcost-db
