version: '2'
services:

  livingcost-db:
    image: 'mongo:latest'
    container_name: 'livingcost-db'
    ports:
      - '27100:27017'
    environment:
      - MONGO_URI=127.0.0.1:27017


  livingcost-ms:
    container_name: 'livingcost-ms'
    build: .
    ports:
      - '3000:3000'

    depends_on:
    - 'livingcost-db'
    environment:
      VIRTUAL_HOST: livingcosts.local
